# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:: /:year/:month/:day/:title/

# Setup
title: Comma Splice
description: Thoughts and links of possible interest
url: https://commasplice.net
timezone: America/New_York

author:
  name: David Dixon
  url: https://bsky.app/profile/david.commasplice.net

paginate: 10

# Custom vars
version: 2025
