# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/
timezone:         America/Denver

# Setup
title:            Comma Splice
description:      Thoughts and links of possible interest
url:              https://commasplice.net/

author:
  name:           David Dixon
  url:            https://twitter.com/davidixon

paginate:         10

# Custom vars
version:          2019
